### ISSUE TITLE
Block sync is stuck on 1 node out of 4

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1511]
**Describe the bug**

Block sync is stuck in v1.3.6 with JS plugin enabled.

JS plugin has no effect on the problem since the network still advances on 3 other machines of the demonet.

**Expected behavior**

Blocks should start syncing.

**Logs**

[node4.log.zip](https://github.com/orbs-network/orbs-network-go/files/3995442/node4.log.zip)
[metrics.json.zip](https://github.com/orbs-network/orbs-network-go/files/3995443/metrics.json.zip)

**Comment by netoneko** [comment]
<img width="689" alt="Screen Shot 2019-12-23 at 17 58 08" src="https://user-images.githubusercontent.com/614125/71367472-d2893a00-25ad-11ea-90ab-fc033407c315.png">

**Comment by electricmonk** [comment]
what do the logs say? does node4 send block availability requests? do the other nodes get them?

**Comment by netoneko** [comment]
All relevant logs are attached.

**Comment by electricmonk** [comment]
you only attached the log for node4
also, can you please extract entries that pertain to block sync from the offending node and other nodes in the same vchain? do some basic filtering and it'll make it much easier for you to get help

**Comment by netoneko** [comment]
Shai, I suggest you take a look at the log, then you can form a hypothesis for a potential production impairing issue.

As for filtering, I suppose that it’s some kind of gossip issue, so if I would filter block sync errors only, it would get us nowhere.

**Comment by electricmonk** [comment]
node4 is apparently failing to communicate via gossip with the other nodes:
```

{"level":"info","timestamp":"2019-12-23T11:30:06.354585993Z","message":"cannot get elected validators from system contract","function":"consensuscontext.(*service).callElectionsSystemContractUntilSuccess","source":"/src/services/consensuscontext/call_contract_elected_validators.go:71","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","service":"consensus-context","error":"unsupported block height: block 457933 is not yet committed: requested future block outside of grace range","block-height":457933,"attempts":1}
{"level":"info","timestamp":"2019-12-23T11:30:08.3283773Z","message":"cannot get elected validators from system contract","function":"consensuscontext.(*service).callElectionsSystemContractUntilSuccess","source":"/src/services/consensuscontext/call_contract_elected_validators.go:71","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","service":"consensus-context","error":"unsupported block height: block 457933 is not yet committed: requested future block outside of grace range","block-height":457933,"attempts":1}
{"level":"info","timestamp":"2019-12-23T11:30:46.125125997Z","message":" failed RequestOrderedCommittee()","function":"leanhelixconsensus.(*membership).RequestOrderedCommittee","source":"/src/services/consensusalgo/leanhelixconsensus/membership.go:58","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","service":"consensus-algo-lean-helix","entry-point":"LeanHelix.Run","request-id":"LeanHelix.Run-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577100606346037819","error":"context terminated during callElectionsSystemContractUntilSuccess"}
{"level":"info","timestamp":"2019-12-23T13:10:22.58315734Z","message":"failed sending keepalive, reconnecting","function":"tcp.(*outgoingConnection).reconnectAfterKeepAliveFailure","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:168","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","adapter":"gossip","peer-node-address":"d27e2e","peer-network-address":"3.123.50.149:4403","entry-point":"Gossip.Transport.TCP.Client.d27e2e","request-id":"Gossip.Transport.TCP.Client.d27e2e-none-1577100603007038147","local-address":"172.18.0.4:33454","error":"attempted to write 4 bytes but only wrote 0: write tcp 172.18.0.4:33454->3.123.50.149:4403: i/o timeout"}
{"level":"info","timestamp":"2019-12-23T15:03:32.332707283Z","message":"failed receiving transport data, disconnecting","function":"tcp.(*transportServer).handleIncomingConnection","source":"/src/services/gossip/adapter/tcp/server.go:162","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","component":"tcp-transport-server","error":"EOF","peer":"10.0.0.2:56262","trace":"NO-CONTEXT"}
{"level":"info","timestamp":"2019-12-23T15:03:36.18608083Z","message":"service block sync failed waiting for block","function":"servicesync.NewServiceBlockSync.func1","source":"/src/services/blockstorage/servicesync/service_sync.go:87","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","service":"block-storage","entry-point":"state-storage-sync","request-id":"state-storage-sync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577100606345753602","error":"aborted while waiting for block at height 527934: context canceled","block-height":527933}
{"level":"info","timestamp":"2019-12-23T15:03:36.186166639Z","message":"service block sync failed waiting for block","function":"servicesync.NewServiceBlockSync.func1","source":"/src/services/blockstorage/servicesync/service_sync.go:87","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","service":"block-storage","entry-point":"tx-pool-sync","request-id":"tx-pool-sync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577100606345764732","error":"aborted while waiting for block at height 527934: context canceled","block-height":527933}
{"level":"info","timestamp":"2019-12-23T15:03:36.525540119Z","message":"failed receiving transport data, disconnecting","function":"tcp.(*transportServer).handleIncomingConnection","source":"/src/services/gossip/adapter/tcp/server.go:162","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","component":"tcp-transport-server","error":"context canceled","peer":"10.0.0.2:57932","trace":"NO-CONTEXT"}
{"level":"info","timestamp":"2019-12-23T15:03:36.536382603Z","message":"failed receiving transport data, disconnecting","function":"tcp.(*transportServer).handleIncomingConnection","source":"/src/services/gossip/adapter/tcp/server.go:162","vcid":1003,"node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","component":"tcp-transport-server","error":"context canceled","peer":"10.0.0.2:34858","trace":"NO-CONTEXT"}
{"level":"info","timestamp":"2019-12-23T15:04:37.418786982Z","message":"cannot get elected validators from system contract","function":"consensuscontext.(*service).callElectionsSystemContractUntilSuccess","source":"/src/services/consensuscontext/call_contract_elected_validators.go:71","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"service":"consensus-context","error":"unsupported block height: block 527933 is not yet committed: requested future block outside of grace range","block-height":527933,"attempts":1}
{"level":"info","timestamp":"2019-12-23T15:04:37.419852616Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"d27e2e","peer-network-address":"3.123.50.149:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113477419786045"}
{"level":"info","timestamp":"2019-12-23T15:04:37.435954009Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"a32884","peer-network-address":"18.196.24.240:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113477419786045"}
{"level":"info","timestamp":"2019-12-23T15:04:37.436007449Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113477419786045"}
{"level":"info","timestamp":"2019-12-23T15:04:44.523860001Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"a32884","peer-network-address":"18.196.24.240:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113484523774679"}
{"level":"info","timestamp":"2019-12-23T15:04:44.524030263Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113484523774679"}
{"level":"info","timestamp":"2019-12-23T15:04:56.610637801Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"a32884","peer-network-address":"18.196.24.240:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113496610575321"}
{"level":"info","timestamp":"2019-12-23T15:04:56.610739714Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113496610575321"}
{"level":"info","timestamp":"2019-12-23T15:05:08.712846635Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"a32884","peer-network-address":"18.196.24.240:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113508712786061"}
{"level":"info","timestamp":"2019-12-23T15:05:08.712928564Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113508712786061"}
{"level":"info","timestamp":"2019-12-23T15:05:20.820670108Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"a32884","peer-network-address":"18.196.24.240:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113520820620423"}
{"level":"info","timestamp":"2019-12-23T15:05:20.820745413Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113520820620423"}
{"level":"info","timestamp":"2019-12-23T15:05:27.144666066Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","trace":"NO-CONTEXT"}
{"level":"info","timestamp":"2019-12-23T15:05:32.838310576Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"a32884","peer-network-address":"18.196.24.240:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113532838218816"}
{"level":"info","timestamp":"2019-12-23T15:05:32.838446942Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113532838218816"}
{"level":"info","timestamp":"2019-12-23T15:05:44.839413257Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","node":"c056dfc0d1fbc7479db11e61d1b0b57612bf7f17","vcid":1003,"adapter":"gossip","peer-node-address":"6e2cb5","peer-network-address":"34.255.219.212:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-c056dfc0d1fbc7479db11e61d1b0b57612bf7f17-1577113544839338760"}
```

Interestingly, there are no logs from BlockSync at all. Is this a new issue? I see a big gap in the log file between 4/12 and 23/12 - what's going on here?

Which network is this? has it been running sporadically?

**Comment by netoneko** [comment]
It happened after I recreated the node replacing EFS with EBS. It had to sync 200k blocks and stuck halfway through the process. I’m not sure if it stuck when I upgraded from 1.3.2 with the plugin to 1.3.6 with the plugin.

The most important part: the node fails to write to the queue, but the metrics say that there are 3 active connections, both incoming and outgoing. But the queues are still disabled despite that.

**Comment by electricmonk** [comment]
Do you have logs from around the time it stuck?
Maybe the metrics lie
Can you check if other nodes are getting block availability responses from this node?

**Comment by netoneko** [comment]
I don't have the logs from the time it got stuck.

Here is a sample from the logs from one of the other nodes:

```
{"level":"info","timestamp":"2019-12-23T11:24:24.52037261Z","message":"failed sending keepalive, reconnecting","function":"tcp.(*outgoingConnection).reconnectAfterKeepAliveFailure","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:168","vcid":1003,"node":"a328846cd5b4979d68a8c58a9bdfeee657b34de7","adapter":"gossip","peer-node-address":"c056df","peer-network-address":"52.56.242.107:4403","entry-point":"Gossip.Transport.TCP.Client.c056df","request-id":"Gossip.Transport.TCP.Client.c056df-none-1577096237641810647","local-address":"172.18.0.4:54422","error":"attempted to write 4 bytes but only wrote 0: write tcp 172.18.0.4:54422->52.56.242.107:4403: i/o timeout"}
{"level":"info","timestamp":"2019-12-23T11:24:25.522027681Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","vcid":1003,"node":"a328846cd5b4979d68a8c58a9bdfeee657b34de7","adapter":"gossip","peer-node-address":"c056df","peer-network-address":"52.56.242.107:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-a328846cd5b4979d68a8c58a9bdfeee657b34de7-1577100265521947170"}
{"level":"info","timestamp":"2019-12-23T11:24:32.522667646Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","vcid":1003,"node":"a328846cd5b4979d68a8c58a9bdfeee657b34de7","adapter":"gossip","peer-node-address":"c056df","peer-network-address":"52.56.242.107:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-a328846cd5b4979d68a8c58a9bdfeee657b34de7-1577100272522589727"}
{"level":"info","timestamp":"2019-12-23T11:24:39.523308449Z","message":"direct transport send queue error","function":"tcp.(*outgoingConnection).addDataToOutgoingPeerQueue","source":"/src/services/gossip/adapter/tcp/outgoing_connection.go:184","vcid":1003,"node":"a328846cd5b4979d68a8c58a9bdfeee657b34de7","adapter":"gossip","peer-node-address":"c056df","peer-network-address":"52.56.242.107:4403","error":"attempted to push to a disabled queue","entry-point":"BlockSync","request-id":"BlockSync-a328846cd5b4979d68a8c58a9bdfeee657b34de7-1577100279523242614"}
```

**Comment by electricmonk** [comment]
52.56.242.107 is the external IP for node4, yes?

notice that `BlockSync.FinishedCollectingAvailabilityResponsesState.FinishedWithSomeResponses.Count` and `BlockSync.CollectingAvailabilityResponsesState.BroadcastSendSuccess.Count` are progressing - although the log you attached doesn't contain any entries for block sync. Which is also weird. So block sync reports that it manages to send availability requests and get responses, but then `BlockSync.WaitingForBlocksState.TimedOutWithoutReceivingBlocks.Count` is also progressing, indicating that no one sends blocks to it.

Can you look at the logs of other nodes, find out if any nodes is getting block requests from this node?
 
If we find nothing at the logs, at this point since we have no logs from when the trouble started, I'd suggest to restart the process, see if it helps. 
also, let's make sure we retain logs for longer periods so that if the issue pops again, we can see what's going on with the logs.

**Comment by netoneko** [comment]
I have updated log retention to 1 week. The problem still persists.

Restarting did not help. I have added your github public key to these machines: 52.56.242.107 (manager) and 3.8.78.136 (worker).

Please investigate.

**Comment by netoneko** [comment]
Grafana links:
* vchain 1003 (node4 is stuck): https://orbsnetwork.grafana.net/d/a-3pW-3mk/orbs-production?orgId=1&from=now-5m&to=now&refresh=10s&var-vchain=1003&var-validator=All
* vchain 1004: https://orbsnetwork.grafana.net/d/a-3pW-3mk/orbs-production?orgId=1&from=now-5m&to=now&refresh=10s&var-vchain=1004&var-validator=All

**Comment by netoneko** [comment]
The port is open and accepts requests:

```
telnet node4.demonet.orbs.com 4403
Trying 52.56.242.107...
Connected to node4.demonet.orbs.com.
Escape character is '^]'.
asdadf
Connection closed by foreign host.
```

**Comment by netoneko** [comment]
List of the nodes:

node1:
* 18.196.24.240
* 3.124.1.36

node2:
* 3.123.50.149
* 18.196.46.37

node3:
* 34.255.219.212 
* 34.245.160.12

node4:
* 52.56.242.107
* 3.8.78.136

**Comment by electricmonk** [comment]
what do the two IP addresses per node mean?

**Comment by electricmonk** [comment]
Ok, this is caused by `chunk-size=5000`.
@jlevison - can you please decrease chunk size to 1000? it should fix the problem.

Apparently around the block where sync stuck, the average block size was just over 4KB; as a result, the chunk size was over 20MB, which is over the maximum size of message the outgoing gossip queue will handle.

@vistra is opening a subsequent bug to document the issue.

**Comment by jlevison** [comment]
@electricmonk thanks!! updating config now, will update here if for some reason it is still unable to sync
